//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ola.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ola.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 你已经对比过一次新对象，不能重复对比变更对象！ 的本地化字符串。
        /// </summary>
        internal static string Differ_Duplicated_Differed {
            get {
                return ResourceManager.GetString("Differ_Duplicated_Differed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原有对象已经初始化，不能重复调用初始化方法！ 的本地化字符串。
        /// </summary>
        internal static string Differ_Duplicated_Initialized {
            get {
                return ResourceManager.GetString("Differ_Duplicated_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象变更原始对象未初始化，请在修改对象时候先调用Init方法。 的本地化字符串。
        /// </summary>
        internal static string Differ_Uninitialized {
            get {
                return ResourceManager.GetString("Differ_Uninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Add {
            get {
                return ResourceManager.GetString("DifferAction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string DifferAction_AddFormat {
            get {
                return ResourceManager.GetString("DifferAction_AddFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Modify {
            get {
                return ResourceManager.GetString("DifferAction_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”由”{1}“修改为“{2}” 的本地化字符串。
        /// </summary>
        internal static string DifferAction_ModifyFormat {
            get {
                return ResourceManager.GetString("DifferAction_ModifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Remove {
            get {
                return ResourceManager.GetString("DifferAction_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string DifferAction_RemoveFormat {
            get {
                return ResourceManager.GetString("DifferAction_RemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹不存在！ 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        internal static string Email_EventType {
            get {
                return ResourceManager.GetString("Email_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件发送服务 的本地化字符串。
        /// </summary>
        internal static string EmailTaskService {
            get {
                return ResourceManager.GetString("EmailTaskService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送队列在数据库中的电子邮件 的本地化字符串。
        /// </summary>
        internal static string EmailTaskService_Description {
            get {
                return ResourceManager.GetString("EmailTaskService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件消息未设置！ 的本地化字符串。
        /// </summary>
        internal static string EventMessage_NullMessage {
            get {
                return ResourceManager.GetString("EventMessage_NullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件消息的用户Id未设置，并且当前用户还未登录！ 的本地化字符串。
        /// </summary>
        internal static string EventMessage_NullUserId {
            get {
                return ResourceManager.GetString("EventMessage_NullUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名称非法，必须以GUID加扩展名的格式！ 的本地化字符串。
        /// </summary>
        internal static string FileNameIsNotGuidFormat {
            get {
                return ResourceManager.GetString("FileNameIsNotGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在！ 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能获取表单文件实例或者文件长度为0！ 的本地化字符串。
        /// </summary>
        internal static string FormFileInvalid {
            get {
                return ResourceManager.GetString("FormFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通会员 的本地化字符串。
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功发送 的本地化字符串。
        /// </summary>
        internal static string MessageStatus_Completed {
            get {
                return ResourceManager.GetString("MessageStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        internal static string MessageStatus_Failured {
            get {
                return ResourceManager.GetString("MessageStatus_Failured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待发送 的本地化字符串。
        /// </summary>
        internal static string MessageStatus_Pending {
            get {
                return ResourceManager.GetString("MessageStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有者 的本地化字符串。
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员角色权限不能被设置！ 的本地化字符串。
        /// </summary>
        internal static string PermissionSetCannotBeOwner {
            get {
                return ResourceManager.GetString("PermissionSetCannotBeOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许 的本地化字符串。
        /// </summary>
        internal static string PermissionValue_Allow {
            get {
                return ResourceManager.GetString("PermissionValue_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止 的本地化字符串。
        /// </summary>
        internal static string PermissionValue_Deny {
            get {
                return ResourceManager.GetString("PermissionValue_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置 的本地化字符串。
        /// </summary>
        internal static string PermissionValue_NotSet {
            get {
                return ResourceManager.GetString("PermissionValue_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定期清理存储文件夹和临时文件夹中得空文件夹或无效文件等 的本地化字符串。
        /// </summary>
        internal static string StorageClearTaskExecutor_Description {
            get {
                return ResourceManager.GetString("StorageClearTaskExecutor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储文件夹清理服务 的本地化字符串。
        /// </summary>
        internal static string StorageClearTaskExecutor_Name {
            get {
                return ResourceManager.GetString("StorageClearTaskExecutor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储文件失败！ 的本地化字符串。
        /// </summary>
        internal static string StoredFileFailured {
            get {
                return ResourceManager.GetString("StoredFileFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功！ 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对数据库中某些列进行分词，生成搜索需求文档，提供前天搜索服务。 的本地化字符串。
        /// </summary>
        internal static string Task_Searching_Description {
            get {
                return ResourceManager.GetString("Task_Searching_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索引擎服务 的本地化字符串。
        /// </summary>
        internal static string Task_Searching_Name {
            get {
                return ResourceManager.GetString("Task_Searching_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [服务]{0}执行错误：{1}。 的本地化字符串。
        /// </summary>
        internal static string TaskExecuteError {
            get {
                return ResourceManager.GetString("TaskExecuteError", resourceCulture);
            }
        }
    }
}
